import { callApi } from '../callApi'

export const hopdongAxios_temp = [
  {
    status: 200,
    message: 'Success',
    success: true,
    data: [
      {
        id_hop_dong: '270',
        id_nhan_vien: '5516',
        ten_hop_dong: 'Hợp Đồng Lao Động',
        so_hop_dong: '195/2025/HĐLĐ-ĐHNCT',
        ngay_bat_dau: '2025-09-06',
        ngay_ket_thuc: '2025-11-05',
        muc_luong: '3000000.00',
        luong_co_ban: null,
        muc_luong_bao_hiem: '0.00',
        id_ty_le_bao_hiem: '4',
        loai_hop_dong: 'Thu_viec',
        file_hop_dong_duong_dan: 'MDAwMDAwMDAwMDAwMDAwMA',
        file_hop_dong_ten_file_goc: null,
        file_hop_dong_loai_file: null,
        ngay_tao: '2025-09-13 15:01:53',
        ngay_sua: '2025-10-27 14:32:52',
        nguoi_tao: '647',
        nguoi_sua: '647',
        deleted_at: null,
        id_vi_tri_cong_viec: '10',
        thoi_han_hop_dong: '2',
        vi_tri_cong_viec: '',
        dang_hieu_luc: '1',
        ti_le_huong_luong: '85.00',
        id_don_vi_cong_tac: '40',
        ngay_ky: '2025-09-06',
        nguoi_dai_dien_ky: 'TS. Trần Hữu Xinh',
        trich_yeu: '123',
        ghi_chu: '123',
        chuc_danh: 'Phó hiệu trưởng',
        files_hop_dong: [],
        hinh_thuc_lam_viec: 'TOAN_THOI_GIAN',
        thong_bao_het_han: '0',
        email: null,
        ma_nhan_vien: '250988',
        ho_va_ten: 'Lê Thúy Vy',
        gioi_tinh: null,
        ngay_sinh: null,
        so_dien_thoai: null,
        avatar: null,
        cccd_so: '900000250988',
        cccd_ngay_cap: null,
        cccd_noi_cap: null,
        mst_ca_nhan: null,
        ma_bhxh: null,
        ten_don_vi: 'Trung tâm PT&ƯDPM DNC',
        ten_cong_viec: 'Nhân viên',
        ten_nguoi_tao: 'Nguyễn Hữu Tấn IT',
        email_nguoi_tao: 'nhtan@nctu.edu.vn',
        path_anh_dai_dien: null,
        phu_cap: [],
        tong_phu_luc: 0,
        ngay_hieu_luc_phu_luc: ''
      },
      {
        id_hop_dong: '268',
        id_nhan_vien: '5545',
        ten_hop_dong: 'Hợp Đồng Lao Động - table last testing',
        so_hop_dong: '193/2025/HĐLĐ-ĐHNCT',
        ngay_bat_dau: '2025-08-27',
        ngay_ket_thuc: '2025-10-26',
        muc_luong: '3000000.00',
        luong_co_ban: '4900000.00',
        muc_luong_bao_hiem: '4900000.00',
        id_ty_le_bao_hiem: '4',
        loai_hop_dong: 'Thu_viec',
        file_hop_dong_duong_dan: 'MDAwMDAwMDAwMDAwMDAwMA',
        file_hop_dong_ten_file_goc: null,
        file_hop_dong_loai_file: null,
        ngay_tao: '2025-09-06 11:27:21',
        ngay_sua: '2025-09-09 08:34:41',
        nguoi_tao: '627',
        nguoi_sua: '647',
        deleted_at: null,
        id_vi_tri_cong_viec: '10',
        thoi_han_hop_dong: '2',
        vi_tri_cong_viec: '',
        dang_hieu_luc: '1',
        ti_le_huong_luong: '100.00',
        id_don_vi_cong_tac: '40',
        ngay_ky: '2025-08-27',
        nguoi_dai_dien_ky: 'TS. Trần Hữu Xinh',
        trich_yeu: '123',
        ghi_chu: '123',
        chuc_danh: 'Nhân viên',
        files_hop_dong: [],
        hinh_thuc_lam_viec: 'TOAN_THOI_GIAN',
        thong_bao_het_han: '0',
        email: null,
        ma_nhan_vien: '251009',
        ho_va_ten: 'Nguyễn Trần Hoàng Long',
        gioi_tinh: '1',
        ngay_sinh: '2003-10-16',
        so_dien_thoai: null,
        avatar: 'uploads/employees/avatars/68ba8950f250d_1757055312.png',
        cccd_so: '312313123213',
        cccd_ngay_cap: null,
        cccd_noi_cap: 'Cục Cảnh sát QLHC về Trật tự xã hội',
        mst_ca_nhan: null,
        ma_bhxh: null,
        ten_don_vi: 'Trung tâm PT&ƯDPM DNC',
        ten_cong_viec: 'Nhân viên',
        ten_nguoi_tao: 'Nguyễn Hữu Tấn Admin',
        email_nguoi_tao: '5tannguyenhuu@gmail.com',
        path_anh_dai_dien:
          'http://localhost/dncoffice_api/uploads/employees/avatars/68ba8950f250d_1757055312.png',
        phu_cap: [],
        tong_phu_luc: 1,
        ngay_hieu_luc_phu_luc: '2025-09-08'
      },
      {
        id_hop_dong: '267',
        id_nhan_vien: '5545',
        ten_hop_dong: 'Hợp Đồng Lao Động - table last testing',
        so_hop_dong: '192/2025/HĐLĐ-ĐHNCT',
        ngay_bat_dau: '2025-08-27',
        ngay_ket_thuc: '2026-07-26',
        muc_luong: null,
        luong_co_ban: '4900000.00',
        muc_luong_bao_hiem: '4900000.00',
        id_ty_le_bao_hiem: '4',
        loai_hop_dong: 'Co_thoi_han',
        file_hop_dong_duong_dan: 'MDAwMDAwMDAwMDAwMDAwMA',
        file_hop_dong_ten_file_goc: null,
        file_hop_dong_loai_file: null,
        ngay_tao: '2025-09-06 11:19:54',
        ngay_sua: '2025-09-09 08:34:26',
        nguoi_tao: '627',
        nguoi_sua: '647',
        deleted_at: null,
        id_vi_tri_cong_viec: '10',
        thoi_han_hop_dong: '12',
        vi_tri_cong_viec: '',
        dang_hieu_luc: '0',
        ti_le_huong_luong: '100.00',
        id_don_vi_cong_tac: '40',
        ngay_ky: '2025-08-27',
        nguoi_dai_dien_ky: 'TS. Trần Hữu Xinh',
        trich_yeu: '123',
        ghi_chu: '123',
        chuc_danh: 'Nhân viên',
        files_hop_dong: [],
        hinh_thuc_lam_viec: 'TOAN_THOI_GIAN',
        thong_bao_het_han: '0',
        email: null,
        ma_nhan_vien: '251009',
        ho_va_ten: 'Nguyễn Trần Hoàng Long',
        gioi_tinh: '1',
        ngay_sinh: '2003-10-16',
        so_dien_thoai: null,
        avatar: 'uploads/employees/avatars/68ba8950f250d_1757055312.png',
        cccd_so: '312313123213',
        cccd_ngay_cap: null,
        cccd_noi_cap: 'Cục Cảnh sát QLHC về Trật tự xã hội',
        mst_ca_nhan: null,
        ma_bhxh: null,
        ten_don_vi: 'Trung tâm PT&ƯDPM DNC',
        ten_cong_viec: 'Nhân viên',
        ten_nguoi_tao: 'Nguyễn Hữu Tấn Admin',
        email_nguoi_tao: '5tannguyenhuu@gmail.com',
        path_anh_dai_dien:
          'http://localhost/dncoffice_api/uploads/employees/avatars/68ba8950f250d_1757055312.png',
        phu_cap: [],
        tong_phu_luc: 0,
        ngay_hieu_luc_phu_luc: ''
      },
      {
        id_hop_dong: '266',
        id_nhan_vien: '5545',
        ten_hop_dong: 'Hợp Đồng Lao Động - table last testing 11',
        so_hop_dong: '191/2025/HĐLĐ-ĐHNCT',
        ngay_bat_dau: '2025-08-27',
        ngay_ket_thuc: '2026-07-26',
        muc_luong: null,
        luong_co_ban: '4900000.00',
        muc_luong_bao_hiem: '4900000.00',
        id_ty_le_bao_hiem: '4',
        loai_hop_dong: 'Co_thoi_han',
        file_hop_dong_duong_dan: 'MDAwMDAwMDAwMDAwMDAwMA',
        file_hop_dong_ten_file_goc: null,
        file_hop_dong_loai_file: null,
        ngay_tao: '2025-09-06 10:52:01',
        ngay_sua: '2025-11-19 08:51:55',
        nguoi_tao: '627',
        nguoi_sua: '627',
        deleted_at: null,
        id_vi_tri_cong_viec: '10',
        thoi_han_hop_dong: '11',
        vi_tri_cong_viec: '',
        dang_hieu_luc: '0',
        ti_le_huong_luong: '100.00',
        id_don_vi_cong_tac: '40',
        ngay_ky: '2025-08-27',
        nguoi_dai_dien_ky: 'TS. Trần Hữu Xinh',
        trich_yeu: '123',
        ghi_chu: '123',
        chuc_danh: 'Nhân viên',
        files_hop_dong: [],
        hinh_thuc_lam_viec: 'TOAN_THOI_GIAN',
        thong_bao_het_han: '0',
        email: null,
        ma_nhan_vien: '251009',
        ho_va_ten: 'Nguyễn Trần Hoàng Long',
        gioi_tinh: '1',
        ngay_sinh: '2003-10-16',
        so_dien_thoai: null,
        avatar: 'uploads/employees/avatars/68ba8950f250d_1757055312.png',
        cccd_so: '312313123213',
        cccd_ngay_cap: null,
        cccd_noi_cap: 'Cục Cảnh sát QLHC về Trật tự xã hội',
        mst_ca_nhan: null,
        ma_bhxh: null,
        ten_don_vi: 'Trung tâm PT&ƯDPM DNC',
        ten_cong_viec: 'Nhân viên',
        ten_nguoi_tao: 'Nguyễn Hữu Tấn Admin',
        email_nguoi_tao: '5tannguyenhuu@gmail.com',
        path_anh_dai_dien:
          'http://localhost/dncoffice_api/uploads/employees/avatars/68ba8950f250d_1757055312.png',
        phu_cap: [],
        tong_phu_luc: 0,
        ngay_hieu_luc_phu_luc: ''
      },
      {
        id_hop_dong: '264',
        id_nhan_vien: '5545',
        ten_hop_dong: 'Hợp Đồng Lao Động - table last testing',
        so_hop_dong: '189/2025/HĐLĐ-ĐHNCT',
        ngay_bat_dau: '2025-08-27',
        ngay_ket_thuc: '2026-07-26',
        muc_luong: null,
        luong_co_ban: '4900000.00',
        muc_luong_bao_hiem: '4900000.00',
        id_ty_le_bao_hiem: '4',
        loai_hop_dong: 'Co_thoi_han',
        file_hop_dong_duong_dan: 'MDAwMDAwMDAwMDAwMDAwMA',
        file_hop_dong_ten_file_goc: null,
        file_hop_dong_loai_file: null,
        ngay_tao: '2025-09-03 16:05:31',
        ngay_sua: '2025-09-09 08:34:51',
        nguoi_tao: '627',
        nguoi_sua: '627',
        deleted_at: null,
        id_vi_tri_cong_viec: '10',
        thoi_han_hop_dong: '11',
        vi_tri_cong_viec: '',
        dang_hieu_luc: '0',
        ti_le_huong_luong: '100.00',
        id_don_vi_cong_tac: '40',
        ngay_ky: '2025-08-27',
        nguoi_dai_dien_ky: 'TS. Trần Hữu Xinh',
        trich_yeu: '123',
        ghi_chu: '123',
        chuc_danh: 'Nhân viên',
        files_hop_dong: [],
        hinh_thuc_lam_viec: 'TOAN_THOI_GIAN',
        thong_bao_het_han: '0',
        email: null,
        ma_nhan_vien: '251009',
        ho_va_ten: 'Nguyễn Trần Hoàng Long',
        gioi_tinh: '1',
        ngay_sinh: '2003-10-16',
        so_dien_thoai: null,
        avatar: 'uploads/employees/avatars/68ba8950f250d_1757055312.png',
        cccd_so: '312313123213',
        cccd_ngay_cap: null,
        cccd_noi_cap: 'Cục Cảnh sát QLHC về Trật tự xã hội',
        mst_ca_nhan: null,
        ma_bhxh: null,
        ten_don_vi: 'Trung tâm PT&ƯDPM DNC',
        ten_cong_viec: 'Nhân viên',
        ten_nguoi_tao: 'Nguyễn Hữu Tấn Admin',
        email_nguoi_tao: '5tannguyenhuu@gmail.com',
        path_anh_dai_dien:
          'http://localhost/dncoffice_api/uploads/employees/avatars/68ba8950f250d_1757055312.png',
        phu_cap: [],
        tong_phu_luc: 0,
        ngay_hieu_luc_phu_luc: ''
      },
      {
        id_hop_dong: '263',
        id_nhan_vien: '5545',
        ten_hop_dong: 'Hợp Đồng Lao Động - table last testing',
        so_hop_dong: '188/2025/HĐLĐ-ĐHNCT',
        ngay_bat_dau: '2025-08-27',
        ngay_ket_thuc: '2026-08-26',
        muc_luong: null,
        luong_co_ban: '4900000.00',
        muc_luong_bao_hiem: '4900000.00',
        id_ty_le_bao_hiem: '4',
        loai_hop_dong: 'Co_thoi_han',
        file_hop_dong_duong_dan: 'MDAwMDAwMDAwMDAwMDAwMA',
        file_hop_dong_ten_file_goc: null,
        file_hop_dong_loai_file: null,
        ngay_tao: '2025-09-03 15:59:19',
        ngay_sua: '2025-09-06 11:27:21',
        nguoi_tao: '627',
        nguoi_sua: '627',
        deleted_at: null,
        id_vi_tri_cong_viec: '10',
        thoi_han_hop_dong: '12',
        vi_tri_cong_viec: '',
        dang_hieu_luc: '0',
        ti_le_huong_luong: '100.00',
        id_don_vi_cong_tac: '40',
        ngay_ky: '2025-08-27',
        nguoi_dai_dien_ky: 'TS. Trần Hữu Xinh',
        trich_yeu: '123',
        ghi_chu: '123',
        chuc_danh: 'Nhân viên',
        files_hop_dong: [],
        hinh_thuc_lam_viec: 'TOAN_THOI_GIAN',
        thong_bao_het_han: '0',
        email: null,
        ma_nhan_vien: '251009',
        ho_va_ten: 'Nguyễn Trần Hoàng Long',
        gioi_tinh: '1',
        ngay_sinh: '2003-10-16',
        so_dien_thoai: null,
        avatar: 'uploads/employees/avatars/68ba8950f250d_1757055312.png',
        cccd_so: '312313123213',
        cccd_ngay_cap: null,
        cccd_noi_cap: 'Cục Cảnh sát QLHC về Trật tự xã hội',
        mst_ca_nhan: null,
        ma_bhxh: null,
        ten_don_vi: 'Trung tâm PT&ƯDPM DNC',
        ten_cong_viec: 'Nhân viên',
        ten_nguoi_tao: 'Nguyễn Hữu Tấn Admin',
        email_nguoi_tao: '5tannguyenhuu@gmail.com',
        path_anh_dai_dien:
          'http://localhost/dncoffice_api/uploads/employees/avatars/68ba8950f250d_1757055312.png',
        phu_cap: [],
        tong_phu_luc: 0,
        ngay_hieu_luc_phu_luc: ''
      },
      {
        id_hop_dong: '262',
        id_nhan_vien: '5545',
        ten_hop_dong: 'Hợp Đồng Lao Động - table last testing',
        so_hop_dong: '187/2025/HĐLĐ-ĐHNCT',
        ngay_bat_dau: '2025-08-27',
        ngay_ket_thuc: '2026-08-26',
        muc_luong: null,
        luong_co_ban: '4900000.00',
        muc_luong_bao_hiem: '4900000.00',
        id_ty_le_bao_hiem: '4',
        loai_hop_dong: 'Co_thoi_han',
        file_hop_dong_duong_dan: 'MDAwMDAwMDAwMDAwMDAwMA',
        file_hop_dong_ten_file_goc: null,
        file_hop_dong_loai_file: null,
        ngay_tao: '2025-09-03 15:54:30',
        ngay_sua: '2025-09-06 11:27:21',
        nguoi_tao: '627',
        nguoi_sua: '627',
        deleted_at: null,
        id_vi_tri_cong_viec: '10',
        thoi_han_hop_dong: '12',
        vi_tri_cong_viec: '',
        dang_hieu_luc: '0',
        ti_le_huong_luong: '100.00',
        id_don_vi_cong_tac: '40',
        ngay_ky: '2025-08-27',
        nguoi_dai_dien_ky: 'TS. Trần Hữu Xinh',
        trich_yeu: '123',
        ghi_chu: '123',
        chuc_danh: 'Nhân viên',
        files_hop_dong: [],
        hinh_thuc_lam_viec: 'TOAN_THOI_GIAN',
        thong_bao_het_han: '0',
        email: null,
        ma_nhan_vien: '251009',
        ho_va_ten: 'Nguyễn Trần Hoàng Long',
        gioi_tinh: '1',
        ngay_sinh: '2003-10-16',
        so_dien_thoai: null,
        avatar: 'uploads/employees/avatars/68ba8950f250d_1757055312.png',
        cccd_so: '312313123213',
        cccd_ngay_cap: null,
        cccd_noi_cap: 'Cục Cảnh sát QLHC về Trật tự xã hội',
        mst_ca_nhan: null,
        ma_bhxh: null,
        ten_don_vi: 'Trung tâm PT&ƯDPM DNC',
        ten_cong_viec: 'Nhân viên',
        ten_nguoi_tao: 'Nguyễn Hữu Tấn Admin',
        email_nguoi_tao: '5tannguyenhuu@gmail.com',
        path_anh_dai_dien:
          'http://localhost/dncoffice_api/uploads/employees/avatars/68ba8950f250d_1757055312.png',
        phu_cap: [],
        tong_phu_luc: 0,
        ngay_hieu_luc_phu_luc: ''
      },
      {
        id_hop_dong: '254',
        id_nhan_vien: '5545',
        ten_hop_dong: 'Hợp Đồng Lao Động - hẹ hẹ - hẹ',
        so_hop_dong: '179/2025/HĐLĐ-ĐHNCT',
        ngay_bat_dau: '2025-08-27',
        ngay_ket_thuc: '2026-08-26',
        muc_luong: null,
        luong_co_ban: '4900000.00',
        muc_luong_bao_hiem: '4900000.00',
        id_ty_le_bao_hiem: '4',
        loai_hop_dong: 'Co_thoi_han',
        file_hop_dong_duong_dan: 'MDAwMDAwMDAwMDAwMDAwMA',
        file_hop_dong_ten_file_goc: null,
        file_hop_dong_loai_file: null,
        ngay_tao: '2025-09-03 08:52:30',
        ngay_sua: '2025-09-09 08:34:55',
        nguoi_tao: '627',
        nguoi_sua: '627',
        deleted_at: null,
        id_vi_tri_cong_viec: '10',
        thoi_han_hop_dong: '12',
        vi_tri_cong_viec: '',
        dang_hieu_luc: '0',
        ti_le_huong_luong: '100.00',
        id_don_vi_cong_tac: '40',
        ngay_ky: '2025-08-27',
        nguoi_dai_dien_ky: 'TS. Trần Hữu Xinh',
        trich_yeu: '123',
        ghi_chu: '123',
        chuc_danh: 'Nhân viên',
        files_hop_dong: [],
        hinh_thuc_lam_viec: 'TOAN_THOI_GIAN',
        thong_bao_het_han: '0',
        email: null,
        ma_nhan_vien: '251009',
        ho_va_ten: 'Nguyễn Trần Hoàng Long',
        gioi_tinh: '1',
        ngay_sinh: '2003-10-16',
        so_dien_thoai: null,
        avatar: 'uploads/employees/avatars/68ba8950f250d_1757055312.png',
        cccd_so: '312313123213',
        cccd_ngay_cap: null,
        cccd_noi_cap: 'Cục Cảnh sát QLHC về Trật tự xã hội',
        mst_ca_nhan: null,
        ma_bhxh: null,
        ten_don_vi: 'Trung tâm PT&ƯDPM DNC',
        ten_cong_viec: 'Nhân viên',
        ten_nguoi_tao: 'Nguyễn Hữu Tấn Admin',
        email_nguoi_tao: '5tannguyenhuu@gmail.com',
        path_anh_dai_dien:
          'http://localhost/dncoffice_api/uploads/employees/avatars/68ba8950f250d_1757055312.png',
        phu_cap: [],
        tong_phu_luc: 6,
        ngay_hieu_luc_phu_luc: '2025-09-05'
      },
      {
        id_hop_dong: '238',
        id_nhan_vien: '4736',
        ten_hop_dong: 'Hợp đồng lao động - Tấn bruh',
        so_hop_dong: '170/2025/HĐLĐ-ĐHNCT',
        ngay_bat_dau: '2025-09-06',
        ngay_ket_thuc: '2026-09-05',
        muc_luong: null,
        luong_co_ban: '4900000.00',
        muc_luong_bao_hiem: '4900000.00',
        id_ty_le_bao_hiem: '4',
        loai_hop_dong: 'Co_thoi_han',
        file_hop_dong_duong_dan: 'MDAwMDAwMDAwMDAwMDAwMA',
        file_hop_dong_ten_file_goc: null,
        file_hop_dong_loai_file: null,
        ngay_tao: '2025-08-27 14:57:31',
        ngay_sua: '2025-09-13 15:01:53',
        nguoi_tao: '627',
        nguoi_sua: '627',
        deleted_at: null,
        id_vi_tri_cong_viec: '10',
        thoi_han_hop_dong: '12',
        vi_tri_cong_viec: '',
        dang_hieu_luc: '0',
        ti_le_huong_luong: '100.00',
        id_don_vi_cong_tac: '40',
        ngay_ky: '2024-12-01',
        nguoi_dai_dien_ky: 'TS. Trần Hữu Xinh',
        trich_yeu: 'Trích yếu nhè',
        ghi_chu: 'Nhè',
        chuc_danh: 'Phó hiệu trưởng',
        files_hop_dong: [],
        hinh_thuc_lam_viec: 'TOAN_THOI_GIAN',
        thong_bao_het_han: '0',
        email: null,
        ma_nhan_vien: '240213',
        ho_va_ten: 'Nguyễn Hữu Tấn Adminnnnnn',
        gioi_tinh: null,
        ngay_sinh: '2001-10-01',
        so_dien_thoai: null,
        avatar: 'uploads/employees/avatars/nguyen_huu_tan_092201001908_01.10.2001.jpg',
        cccd_so: '092201001908',
        cccd_ngay_cap: '2023-09-01',
        cccd_noi_cap: 'Cục Trưởng Cục Cảnh Sát',
        mst_ca_nhan: null,
        ma_bhxh: null,
        ten_don_vi: 'Trung tâm PT&ƯDPM DNC',
        ten_cong_viec: 'Nhân viên',
        ten_nguoi_tao: 'Nguyễn Hữu Tấn Admin',
        email_nguoi_tao: '5tannguyenhuu@gmail.com',
        path_anh_dai_dien:
          'http://localhost/dncoffice_api/uploads/employees/avatars/nguyen_huu_tan_092201001908_01.10.2001.jpg',
        phu_cap: [],
        tong_phu_luc: 0,
        ngay_hieu_luc_phu_luc: ''
      },
      {
        id_hop_dong: '237',
        id_nhan_vien: '4651',
        ten_hop_dong: 'Hợp Đồng Lao Động',
        so_hop_dong: '169/2025/HĐLĐ-ĐHNCT',
        ngay_bat_dau: '2025-08-25',
        ngay_ket_thuc: '2026-08-24',
        muc_luong: null,
        luong_co_ban: '5490000.00',
        muc_luong_bao_hiem: '5490000.00',
        id_ty_le_bao_hiem: '4',
        loai_hop_dong: 'Co_thoi_han',
        file_hop_dong_duong_dan: 'MDAwMDAwMDAwMDAwMDAwMA',
        file_hop_dong_ten_file_goc: null,
        file_hop_dong_loai_file: null,
        ngay_tao: '2025-08-25 18:23:57',
        ngay_sua: '2025-10-25 10:23:50',
        nguoi_tao: '627',
        nguoi_sua: '627',
        deleted_at: null,
        id_vi_tri_cong_viec: '10',
        thoi_han_hop_dong: '12',
        vi_tri_cong_viec: '',
        dang_hieu_luc: '0',
        ti_le_huong_luong: '100.00',
        id_don_vi_cong_tac: '57',
        ngay_ky: '2025-08-25',
        nguoi_dai_dien_ky: 'TS. Trần Hữu Xinh',
        trich_yeu: '123',
        ghi_chu: '123',
        chuc_danh: 'Phó hiệu trưởng',
        files_hop_dong: [],
        hinh_thuc_lam_viec: 'TOAN_THOI_GIAN',
        thong_bao_het_han: '0',
        email: null,
        ma_nhan_vien: '250128',
        ho_va_ten: 'Trần Trọng Nguyễn',
        gioi_tinh: null,
        ngay_sinh: '2002-07-01',
        so_dien_thoai: null,
        avatar: 'uploads/employees/avatars/tran_trong_nguyen_096202005350_01.07.2002.jpg',
        cccd_so: '096202005350',
        cccd_ngay_cap: '2021-08-14',
        cccd_noi_cap: 'Cục Cảnh sát quản lý hành chính về trật tự xã hội.',
        mst_ca_nhan: null,
        ma_bhxh: null,
        ten_don_vi: 'Phòng CTCT & QLSV',
        ten_cong_viec: 'Nhân viên',
        ten_nguoi_tao: 'Nguyễn Hữu Tấn Admin',
        email_nguoi_tao: '5tannguyenhuu@gmail.com',
        path_anh_dai_dien:
          'http://localhost/dncoffice_api/uploads/employees/avatars/tran_trong_nguyen_096202005350_01.07.2002.jpg',
        phu_cap: [],
        tong_phu_luc: 2,
        ngay_hieu_luc_phu_luc: '2025-08-26'
      }
    ],
    recordsTotal: 41,
    recordsFiltered: 38
  }
]
export const INITIAL_VISIBLE_COLUMNS = [
  'stt',
  'ten_nguoi_tao',
  'dang_hieu_luc',
  'so_hop_dong',
  'ho_va_ten',
  'ngay_bat_dau',
  'ngay_ket_thuc',
  'tong_phu_luc',
  'luong_co_ban',
  'muc_luong_bao_hiem',
  'muc_luong'
]

export interface TableColumn {
  uid: string
  name: string
  className?: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  render?: (value: any, row?: any) => React.ReactNode
}

export const columns: TableColumn[] = [
  { uid: 'ten_nguoi_tao', name: 'Người soạn', className: '' },
  { uid: 'dang_hieu_luc', name: 'Trạng thái', className: '' },
  { uid: 'so_hop_dong', name: 'Số hợp đồng', className: '' },
  { uid: 'ho_va_ten', name: 'Họ tên', className: '' },
  { uid: 'ngay_bat_dau', name: 'Bắt đầu', className: '' },
  { uid: 'ngay_ket_thuc', name: 'Kết thúc', className: 'w-20_' },
  { uid: 'tong_phu_luc', name: 'Tổng số phụ lục', className: 'w-20_' },
  { uid: 'muc_luong_bao_hiem', name: 'Mức lương bảo hiểm', className: 'w-26_' },
  { uid: 'luong_co_ban', name: 'Lương cơ bản', className: 'w-26_' },
  { uid: 'muc_luong', name: 'Mức lương', className: 'w-26_' }
]

export const hopdongAxios = {
  fetch: (payload?: object) => {
    return callApi('admin/hrm/hopdong', {
      method: 'GET',
      data: payload
    })
  },
  show: (id: string | number) => {
    return callApi(`admin/hrm/hopdong/show/${id}`, {
      method: 'GET'
    })
  },
  create: (data: object) => {
    return callApi('admin/hrm/hopdong/create', {
      method: 'POST',
      data: data
    })
  },
  update: (id: string | number, data: object) => {
    return callApi(`admin/hrm/hopdong/update/${id}`, {
      method: 'POST',
      data: data
    })
  },
  delete: (data: object) => {
    return callApi('admin/hrm/hopdong/delete', {
      method: 'POST',
      data: data
    })
  },
  files: (payload?: object) => {
    // Lấy danh sách file đính kèm
    return callApi(`admin/vanban/vanbandi/files_v2`, {
      method: 'POST',
      data: payload
    })
  },
  hopdongcuoi: (id: string | number) => {
    return callApi(`admin/hrm/hopdong/hopdongcuoi/${id}`, {
      method: 'GET'
    })
  },
  tylebaohiem: () => {
    return callApi(`admin/danhmuc/hrm/tylebaohiem/latest`, {
      method: 'GET'
    })
  },
  xemluongcoban: (id: string | number) => {
    return callApi(`admin/hrm/hopdong/xemluongcoban/${id}`, {
      method: 'GET'
    })
  },
  xemphuluc: (id: string | number) => {
    return callApi(`admin/hrm/hopdong/xemphuluc/${id}`, {
      method: 'GET'
    })
  },
  themphuluc: (data: object) => {
    return callApi(`admin/hrm/hopdong/themphuluc`, {
      method: 'POST',
      data: data
    })
  },
  lichsu: (payload?: object) => {
    return callApi(`admin/hrm/hopdong/view_log`, {
      method: 'GET',
      data: payload
    })
  }
}
